// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYvA3SnQxPU-aT_ol26dsfMyJqz6hOyU',
    appId: '1:200842013574:web:c0036df1928d4e0a979a07',
    messagingSenderId: '200842013574',
    projectId: 'batch-32-b',
    authDomain: 'batch-32-b.firebaseapp.com',
    storageBucket: 'batch-32-b.appspot.com',
    measurementId: 'G-TSQMSWTZPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOGCX-8O7OhFUge18BjAgm13bT98BVyo',
    appId: '1:200842013574:android:300b0c730e653538979a07',
    messagingSenderId: '200842013574',
    projectId: 'batch-32-b',
    storageBucket: 'batch-32-b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KxxKW92m0OT8KczH3g4kU9cdEWv8BlA',
    appId: '1:200842013574:ios:276891c7dd67641e979a07',
    messagingSenderId: '200842013574',
    projectId: 'batch-32-b',
    storageBucket: 'batch-32-b.appspot.com',
    iosClientId: '200842013574-rhvmp7d1pse74nslu0gvpf1vjvnehrn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KxxKW92m0OT8KczH3g4kU9cdEWv8BlA',
    appId: '1:200842013574:ios:276891c7dd67641e979a07',
    messagingSenderId: '200842013574',
    projectId: 'batch-32-b',
    storageBucket: 'batch-32-b.appspot.com',
    iosClientId: '200842013574-rhvmp7d1pse74nslu0gvpf1vjvnehrn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
